### ISSUE TITLE
resnet.preprocessing.py

### ISSUE THREAD

**Issue by GodsDusk** [qubvel/classification_models#1]
hi
I saw the code of preprocessing.py that
`x = resize(x, size) * 255`
when read a image use skiamge, the range of pixel is in [0, 255], so you multiply 255 means pretrained model are trained in [0, 65025] ?

**Comment by qubvel** [comment]
@GodsDusk after resizing image will be in range 0-1 as `float`, model has been trained for `uint8` data type in range 0-255
