### ISSUE TITLE
Edit model fine tuning example

### ISSUE THREAD

**Issue by AlfTetzlaff** [qubvel/classification_models#13]
Hey, I suggest that you change the model fine tuning example in two points:
1) Change AveragePooling2D to GlobalAveragePooling2D
2) Add a softmax layer. I was so retarded to try to optimize a model without for two hours.
Thanks :D

**Comment by qubvel** [comment]
Yes, you are right, good catch! Thank you, I will change it.

**Comment by AlfTetzlaff** [comment]
Thanks!
