### ISSUE TITLE
Update model link in weights.py

### ISSUE THREAD

**Issue by praveng** [qubvel/classification_models#22]
Would you mind updating the link in weights.py  from https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet50_places365_11586.h5

to 

https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet50_imagenet_11586.h5 

Also, do you know where I could find the corresponding labels for the classes?

**Comment by qubvel** [comment]
Hi @praveng 
Now link is https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet50_imagenet11k-places365ch_11586.h5
Should work fine!
