### ISSUE TITLE
SE-Resnet 101 pretrained models in Mxnet?

### ISSUE THREAD

**Issue by Magic-chao** [qubvel/classification_models#24]
I have try MMdnn to convert pretrained model in [pytorch](https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/senet.py) and [keras](https://github.com/qubvel/classification_models/blob/ca4888745266cee2da1384259e9fd4c065dcf5bd/classification_models/weights.py#L219) you provided but failed! When and Where can I find the SE-Resnet101 pretrained model in mxnet version？Thank you！

**Comment by qubvel** [comment]
Hi @Magic-chao 
Yeah, MMdnn is not a perfect tool, but I was able to convert models step by step with some fixes of created intermediate code and weights. It actually takes about several days to find a way.

**Comment by Magic-chao** [comment]
@qubvel em. So how can I solve the problem? Can you give me some advices , it really comfused me for a few days.

**Comment by qubvel** [comment]
Look at https://github.com/osmr/imgclsmob/tree/master/gluon 
Gluon has MXNet backend, so maybe it will be easy to port it to pure MXNet

**Comment by Magic-chao** [comment]
Thanks very much!  I will try it.
