### ISSUE TITLE
Couldn't download ResNet50 for imagenet

### ISSUE THREAD

**Issue by Xiaocong6** [qubvel/classification_models#26]
Hi, I have a trouble. I'm in great need of your assistance. 
I couldn't download the pretrained model for ResNet50 from "https://github.com/qubvel/classification_models/releases/download/0.0.1/resnet50_imagenet_1000_no_top.h5".
It will terminate when I download it to more than 30MB.
In linux, It prompts such an error “Connection reset by peer”
In windows, I downloaded it in the browser and it prompts "Failed - has been banned".
I have tried many times and failed. How can I download the file-resnet50_imagenet_1000_no_top.h5?

Thanks a lot!

**Comment by qubvel** [comment]
Hi @Xiaocong6 
Dont know how to help you, check your internet/vpn provider.

**Comment by Xiaocong6** [comment]
Thanks! I tried it again and finally succeeded! Thanks again!
