### ISSUE TITLE
Resnet models

### ISSUE THREAD

**Issue by tinalegre** [qubvel/classification_models#28]
It looks that your own RestNet implementation is based on Resnet Version 2 (Preact / BN->Relu->Conv). Could you  please also consider adding ResNet Version 1 (code + pre-trained weights)? I'm unfortunately limited on GPU resources and can't therefore do a full train in imagenet, etc. I know that keras-applications has both V1/V2, but I find that your toolbox is better organized.

**Comment by qubvel** [comment]
Hi @tinalegre 
I did not train any of models, just convert or transfer weights from other frameworks/repos.
If you will find such pretrained models I will consider such option. Models from keras_applications are inside of this repo.

**Comment by tinalegre** [comment]
Hi @qubvel thank you. I was wondering why on your ResNet model, just after the last residual block and before the top classification layer, we need to have the additional [BN](https://github.com/qubvel/classification_models/blob/fb583175cebd812a916211c141b32e11e12acfb6/classification_models/resnet/builder.py#L99)+[Relu](https://github.com/qubvel/classification_models/blob/fb583175cebd812a916211c141b32e11e12acfb6/classification_models/resnet/builder.py#L100) layers (named respectively `bn1` and `relu1`)?

**Comment by qubvel** [comment]
Once again:
ResNet models was not created by me. I have just rewrite architecture from MXNet models zoo as it is and convert weights.
So the answer to your question is: "Because they have been created and trained with such architecture by someone (I actually don`t know the authors of this implementation and their motivation)"
