### ISSUE TITLE
ImportError: No module named classification_models.keras

### ISSUE THREAD

**Issue by matak07** [qubvel/classification_models#36]
When I try to import classification_models.keras for using ResNet18, I am getting an ImportError as:
from classification_models.tfkeras import Classifiers
ImportError: No module named classification_models.tfkeras

I am using Ubuntu 16.04 OS with Python3.5, Keras 2.2.4, Keras-applications 1.0.8 and Tensorflow 1.13.1.
Please advise as I am unable to figure out why the error.

Thanks in advance.

**Comment by qubvel** [comment]
Hi, please update to 1.* Version

**Comment by Choikey11** [comment]
> Hi, please update to 1.* Version

update whose version？

**Comment by mz185075** [comment]
> > Hi, please update to 1.* Version
> 
> update whose version？

He means pip install image-classifiers==1.0.0b1

**Comment by AlexandreBourrieau** [comment]
Same problem using pip install image-classifiers==1.0.0b1 do not help...
