### ISSUE TITLE
About preprocessing

### ISSUE THREAD

**Issue by JoeyTPChou** [qubvel/classification_models#37]
Hi, 

This repo is fantastic!

I have questions about the preprocessing part. I only saw 'return x' in the preprocess_input in resnet.py. Is that true for all the resnet pretrained models?

Also, for the input tensor, does it expect 'RGB' or 'BGR'? 

Thanks!
Joey

**Comment by qubvel** [comment]
Hi, thanks,
resnet models have been trained on RGB images with range 0-255 (uint8)
Just read images in RGB uint8 and use preprcessing_function -> dont think about it ))

**Comment by JoeyTPChou** [comment]
Hi, 

Thanks for quick response!
