### ISSUE TITLE
Expected Range for Inputs (also for segmentation models)

### ISSUE THREAD

**Issue by gkaissis** [qubvel/classification_models#45]
From the tutorial it seems like all preprocessing functions for pretrained models expect 8 bit RGB images in the range 0-255. From what I understand, this is also true for all pretrained models in segmentation_models. Can you please confirm that this is the case for **all** models in **both** libraries?  

#37 confirms this for ResNets

Thank you very much!

**Comment by qubvel** [comment]
Confirm

**Comment by gkaissis** [comment]
Thank you very much!
