### ISSUE TITLE
4 channel

### ISSUE THREAD

**Issue by MinuteswithMetrics** [qubvel/classification_models#5]
Thanks again for the wonderful library! This is very helpful and I  learned a lot by studying your code. Is it possible to edit the code from (height,width, 3) to (height,width, 4)? If so were can I update the code?

**Comment by qubvel** [comment]
Hi @MinuteswithMetrics,
1) You can change input shape as follows:
```python
model = Unet('resnet34', input_shape=(None, None, 4), encoder_weights=None)
```
2) If you still want to use pretrained encoder, download weights and load them by name:
```python
model.load_weights('/path/to_weights.hdf5', by_name=True)
```
In this case, the first layer will be initialized randomly, so I recommend you to freeze layers with transferred weights and tune other layers at least some epochs.

**Comment by MinuteswithMetrics** [comment]
Thank you qubvel.
