### ISSUE TITLE
input images for ResNet

### ISSUE THREAD

**Issue by RicSpd** [qubvel/classification_models#6]
Hi qubvel, thanks for your great repo.

I would like to ask a question, just to clarify the ideas I have in mind. If I understood correctly your code and the previous issues, the ResNet models you define in _models.py_ and their corresponding weights are trained using data in [0, 255] range and coded as BGR, correct?

Therefore, if I import an image in RGB using `img = imread(...)`, I don't need to rescale it into [0,1] range but I need to "transpose" it using your function `img = preprocess_input(img, BGRTranspose = True)` and then use the ResNet model, am I right?

**Comment by qubvel** [comment]
Hi @RicSpd, 
Just today I made validation of ResNet models and realize that they perform better without BGR transpose. So just read image in `uint8` (RGB [0, 255]), resize and pass through the network!

P.S. Make sure image during resizing did not become `float` [0, 1]

**Comment by qubvel** [comment]
This update will be soon with new models, you can check feature-se branch :smile:

**Comment by bityangke** [comment]
@qubvel 
Thanks very much for sharing!
I have a question. Why not subtract the mean value for resnet input?
