### ISSUE TITLE
AttributeError: module 'keras.utils' has no attribute 'get_file'

### ISSUE THREAD

**Issue by jeannechaverot** [qubvel/classification_models#68]
Hello, first of all thank you very much for writing these models. I've been using your implementation for the past 3 months and they worked perfectly until I updated my libraries. 

When I try to run the simple code snippet below on Google Colab:

```
from classification_models.keras import Classifiers

ResNet18, preprocess_input = Classifiers.get('resnet18')
resnet = ResNet18((170, 170, 3), weights='imagenet', include_top=False)
```

I get the following error:

```
AttributeError: module 'keras.utils' has no attribute 'get_file'
```

Any idea why? Thank you in advance!

**Comment by programandoconro** [comment]
https://stackoverflow.com/questions/68032028/attributeerror-module-keras-utils-has-no-attribute-get-file-using-classific/68032707?noredirect=1#comment120245794_68032707
